services:
  #frontend:
  
  backend:
    build:
      context: ./Backend
    env_file:
      - .env
    expose:
      - "8000"
    networks:
      - app-network
    depends_on:
      - db

  db:
    image: postgres:17
    env_file:
      - .env
    ports:
      - "5432:5432"
    networks:
      - app-network

  nginx:
    build:
      context: ./nginx
    ports:
      - "8080:443"
    depends_on:
      - frontend
      - backend
    networks:
      - app-network


networks:
  app-network:
    driver: bridge