[tool.black]
line-length = 88
target-version = ['py310']
extend-exclude = '''
/(
    migrations
  | node_modules
  | venv
  | \.venv
)/
'''

[tool.isort]
profile = "black"
line_length = 88
skip = ["migrations", "node_modules", "venv", ".venv"]

[tool.mypy]
python_version = "3.10"
plugins = ["mypy_django_plugin.main"]
django_settings_module = "shmooz.settings"
ignore_missing_imports = true
exclude = "migrations/|node_modules/|venv/|.venv/"
