# Generated by Django 5.2.1 on 2025-05-10 02:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0001_initial'),
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('text', models.CharField(max_length=50)),
                ('text_color', models.CharField(max_length=50)),
                ('label_letter', models.CharField(max_length=2)),
                ('label_color', models.CharField(max_length=50)),
                ('inline_color', models.CharField(max_length=50)),
                ('owner', models.CharField(max_length=50)),
                ('deckTitle', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_cards', to='administration.imageupload')),
            ],
        ),
    ]
