# Generated by Django 5.2.1 on 2025-05-14 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_projectcard'),
    ]

    operations = [
        migrations.CreateModel(
            name='SlugEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='deck',
            name='edited_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectcard',
            name='edited_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
