# Generated by Django 5.2.1 on 2025-05-15 01:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_slugentry_deck_edited_at_projectcard_edited_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectcard',
            name='deckTitle',
        ),
        migrations.AddField(
            model_name='projectcard',
            name='deck',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_cards', to='portfolio.deck'),
        ),
    ]
