# Generated by Django 5.2.1 on 2025-05-29 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_remove_projectcard_decktitle_projectcard_deck'),
    ]

    operations = [
        migrations.CreateModel(
            name='PagesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.SlugField()),
                ('category', models.CharField(choices=[('page1', 'Page 1'), ('page2', 'Page 2')], max_length=20)),
                ('content', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('edited_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'unique_together': {('owner', 'category')},
            },
        ),
    ]
