# Generated by Django 5.2.1 on 2025-05-29 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_pagesmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagesmodel',
            name='category',
            field=models.CharField(choices=[('page_one', 'Page 1'), ('page_two', 'Page 2')], max_length=20),
        ),
    ]
