# Generated by Django 5.2.1 on 2025-05-31 22:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_alter_pagesmodel_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagesmodel',
            name='project_card',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='page', to='portfolio.projectcard'),
        ),
    ]
