# Generated by Django 5.2.1 on 2025-05-31 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0007_pagesmodel_project_card'),
    ]

    operations = [
        migrations.CreateModel(
            name='BackgroundData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.CharField(max_length=50)),
                ('color1', models.CharField(max_length=50)),
                ('color2', models.CharField(max_length=50)),
                ('color3', models.CharField(max_length=50)),
                ('position1', models.CharField(max_length=50)),
                ('position2', models.CharField(max_length=50)),
                ('position3', models.CharField(max_length=50)),
                ('page1', models.CharField(max_length=50)),
                ('page2', models.CharField(max_length=50)),
            ],
        ),
    ]
