# Generated by Django 5.2.4 on 2025-07-24 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0008_backgrounddata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagesmodel',
            name='category',
            field=models.CharField(max_length=50),
        ),
    ]
