# Generated by Django 5.2.5 on 2025-08-06 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0011_deck_hover_brightness_deck_hover_rotations_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='backgrounddata',
            name='arrowColor',
            field=models.CharField(default='#FFFFFF', max_length=50),
        ),
        migrations.AddField(
            model_name='backgrounddata',
            name='ellipseHeight',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='backgrounddata',
            name='ellipseWidth',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='backgrounddata',
            name='navColor',
            field=models.CharField(default='#000000', max_length=50),
        ),
    ]
