# Generated by Django 5.2.5 on 2025-08-12 16:15

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0002_alter_imageupload_options'),
        ('portfolio', '0012_backgrounddata_arrowcolor_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deck',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='projectcard',
            options={'ordering': ['id']},
        ),
        migrations.AddField(
            model_name='backgrounddata',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='backgrounddata',
            name='edited_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='slugentry',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='slugentry',
            name='edited_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='deck',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='deck',
            name='edited_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='projectcard',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='projectcard',
            name='edited_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddIndex(
            model_name='deck',
            index=models.Index(fields=['-edited_at'], name='portfolio_d_edited__0f8919_idx'),
        ),
        migrations.AddIndex(
            model_name='deck',
            index=models.Index(fields=['-created_at'], name='portfolio_d_created_3b37dc_idx'),
        ),
        migrations.AddIndex(
            model_name='projectcard',
            index=models.Index(fields=['-edited_at'], name='portfolio_p_edited__a8f407_idx'),
        ),
        migrations.AddIndex(
            model_name='projectcard',
            index=models.Index(fields=['-created_at'], name='portfolio_p_created_de3e4f_idx'),
        ),
    ]
