# Generated by Django 5.2.5 on 2025-08-15 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0013_alter_deck_options_alter_projectcard_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deck',
            name='text_color',
            field=models.CharField(default='#fff', max_length=50),
            preserve_default=False,
        ),
    ]
