# Generated by Django 5.2.5 on 2025-08-19 16:13

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0014_deck_text_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='deck',
            name='hover_color',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
