# Generated by Django 5.2.5 on 2025-08-12 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='imageupload',
            options={'ordering': ['id']},
        ),
    ]
