# Generated by Django 5.2.5 on 2025-08-25 15:54

import administration.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0002_alter_imageupload_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageupload',
            name='image',
            field=models.ImageField(upload_to=administration.models.upload_to_uploads),
        ),
    ]
